//! The help panel's contents: what it says, and which row runs what.
//!
//! Kept out of `tui.rs` because this is text, not behaviour — a hundred and
//! forty lines of prose that used to sit in the middle of the renderer and
//! made both harder to read. The rendering (the box, the scrolling, the
//! clickable rows) stays with the rest of the drawing, in the parent.
//!
//! Since every row of this panel is also a CLICKABLE command, the two things
//! here belong together: change a row's leading key and [`action`] is the one
//! place that has to agree with it.

use super::*;

/// The action a help row runs when clicked, or 0 for the rows that are only
/// legend.
///
/// The key shown at the start of a row IS the row's identity, so it is what
/// this keys on: no parallel list to keep in step with the text.
pub(super) fn action(key: &str) -> u16 {
    // La PRIMA parola, non un prefisso qualunque. Con `starts_with` la riga
    // «find <testo>» — che documenta il comando da terminale `phosphor find` —
    // cominciava per «f» e diventava il filtro di stato: cliccare una
    // spiegazione cambiava un'impostazione. Una riga e' un comando solo se la
    // sua chiave E' quel comando.
    //
    // Le righe doppie («r  ·  e») eseguono la prima: e' il titolo della riga.
    match key.split_whitespace().next().unwrap_or("") {
        "⏎" => A_DETAIL,
        "v" => A_READ,
        "g" => A_GSEARCH,
        "M" => A_MARKDOWN,
        "N" => A_ALIAS,
        "a" => A_AGENTS,
        "/" => A_SEARCH,
        "m" => A_METRIC,
        "A" => A_EXPAND_ALL,
        "H" => A_ARCHIVE,
        "W" => A_WRAPPED,
        "V" => A_VAULT_RESTORE,
        "F" => A_FLEET,
        "D" => A_DELPROJECT,
        "*" => A_FAVORITE,
        "O" => A_OPENFOLDER,
        "f" => A_FILTER,
        "r" => A_RESUME,
        "x" => A_EXPBUNDLE,
        "t/T" => A_THEME_NEXT,
        "R" => A_RESCAN,
        _ => 0,
    }
}

/// Le chiavi che sono comandi. Serve al test che controlla che nessuna riga
/// diventi cliccabile per sbaglio: e' l'elenco completo, e deve restare
/// d'accordo con [`action`].
#[cfg(test)]
pub(super) const COMMAND_KEYS: [&str; 21] = [
    "⏎", "v", "g", "M", "N", "a", "/", "m", "A", "H", "W", "V", "F", "D", "*", "O", "f", "r", "x",
    "t/T", "R",
];

/// Every line of the panel, styled, in the language in use. `'static` because
/// the text is all literals and the caller scrolls it.
pub(super) fn lines(th: &Theme) -> Vec<Line<'static>> {
    if crate::lang::is_en() {
        lines_en(th)
    } else {
        lines_it(th)
    }
}

/// Il pannello in italiano.
/// Every line of the panel, styled. `'static` because the text is all literals
/// and the caller scrolls it.
fn lines_it(th: &Theme) -> Vec<Line<'static>> {
    let item = |k: &str, d: &str| Line::from(vec![
        Span::styled(format!("  {:<12}", k), Style::default().fg(th.accent)),
        Span::styled(d.to_string(), Style::default().fg(th.fg)),
    ]);
    vec![
        Line::raw(""),
        Line::from(Span::styled("  LEGENDA SIMBOLI", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↳", "sessione ripresa o da /compact (continua la precedente)"),
        item("★ · 📝 · ◉", "preferito  ·  ha una nota  ·  selezionata (multi-select)"),
        item("◆", "sessione Codex (~/.codex/sessions) invece che Claude Code: nome del progetto in un altro colore, riprende con  codex resume . Filtro:  agent:codex . Token e costo sono quelli di OpenAI (prezzi \"gpt\" in phosphor.json)."),
        item("⚠ cronologia", "Claude Code cancella i suoi transcript dopo  cleanupPeriodDays  giorni — 30 di default, all'avvio, senza cestino: è così che spariscono i progetti fermi da un mese. Phosphor te lo chiede al primo avvio; puoi anche farlo da riga di comando con  phosphor retention 3650  (cambia solo quel numero in ~/.claude/settings.json e tiene una copia del file). Codex non ha nulla di simile: non pota per data. Contro tutto il resto — pulitori disco, sync, cancellazioni a mano — serve  phosphor vault on ."),
        item("⛁", "salvata dal vault: il suo agente ha cancellato il transcript, che però sopravvive come hard link in ~/.claude/phosphor-vault. È completa — token, conversazione, tutto — e  V  la rimette al suo posto, tornando riprendibile. Si accende con  phosphor vault on  (spento di default: è l'unica cosa che scrive su disco)."),
        item("⚱", "recuperata da history.jsonl: il transcript l'ha cancellato Claude Code (cleanupPeriodDays, 30 giorni di default). Restano i prompt; niente risposte, token, costo o riprendi. Alza cleanupPeriodDays in ~/.claude/settings.json per non perderne altre."),
        item("● ◐ ·", "stato:  ● attiva   ◐ in pausa (idle)   · conclusa"),
        item("⏎", "tasto Invio (apre il dettaglio della sessione)"),
        item("↑ ↓", "frecce su/giù (muovono la selezione)"),
        Line::from(Span::styled("  In alto a destra scorrono pillole d'uso (› …).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  COMANDI RAPIDI", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↑↓ / scroll", "muovi selezione (senza aprire)"),
        item("Invio / click", "apri dettaglio della sessione"),
        item("destro / .", "menù sessione: tutte le azioni in un colpo solo"),
        item("+ / -", "espandi/comprimi le riprese della conversazione selezionata"),
        item("A", "espandi/comprimi TUTTE le riprese in una volta"),
        item("⟳N ✓ / (certo)", "link PROVATO (le sessioni condividono messaggi)"),
        item("(probabile)", "raggruppamento STIMATO da titolo+progetto+tempo"),
        item("v", "leggi la conversazione (transcript) in-app"),
        item("g", "cerca nel CONTENUTO di tutte le conversazioni → apri al punto"),
        item("M", "esporta la conversazione in Markdown (sul Desktop)"),
        item("*  ·  n", "preferito (★)  ·  nota sulla sessione (📝)"),
        item("N", "rinomina: titolo/alias tuo mostrato in lista al posto di quello automatico"),
        item("O  ·  y", "apri la cartella del progetto  ·  copia il percorso del transcript"),
        item("spazio", "seleziona/deseleziona (◉) per azioni in blocco  ·  Esc azzera"),
        item("in blocco", "con selezione attiva:  x bundle  ·  * preferiti  ·  X cancella (conferma)"),
        item("a", "esplora sub-agenti / workflow"),
        item("/", "filtra la lista — testo + filtri: project: model: file: tool: agent: host: after: before:"),
        item("f  ·  o/s", "filtro stato/★preferiti  ·  ordina colonna/direzione"),
        item("m", "metrica grafici (o click sui bottoni)"),
        item("r  ·  e", "riprendi (claude --resume)  ·  export CSV/JSON"),
        item("x  ·  i", "esporta bundle .phx  ·  importa (selettore file + conferma)"),
        item("H", "ARCHIVIA il progetto (lo nasconde in archived/, reversibile) — ripristina da CLI"),
        item("W", "WRAPPED: genera sul Desktop la card riassuntiva dell'anno (PNG + SVG) — token, costo, energia, acqua. Anonima: solo numeri."),
        item("V", "RIPRISTINA dal vault: rimette il transcript nel magazzino del suo agente (solo righe ⛁)"),
        item("F", "FLOTTA: interroga i tuoi altri PC via ssh e unisce le loro sessioni [alias]"),
        item("", "  (configura con:  phosphor remote add <alias-ssh> · su remoto: r riprende LÀ)"),
        item("D", "CANCELLA il progetto della sessione (doppia conferma: riscrivi il nome; offre backup .phx)"),
        item("t/T  ·  p", "tema avanti/indietro  ·  grafica pixel"),
        item("R  ·  Tab", "rescan  ·  cambia vista (o 1 2 3)  ·  q esci"),
        Line::raw(""),
        Line::from(Span::styled("  Da terminale  ›  phosphor …", Style::default().fg(th.accent))),
        item("find <testo>", "ricerca full-text in tutte le sessioni"),
        item("cost", "spesa 24h/7g/30g · budget · top progetti"),
        item("limits", "piano (es. Max 20x) · reset finestra limiti"),
        item("watch", "monitor live con avvisi di stato"),
        item("clean", "spazio disco · pulizia vuote (con conferma)"),
        item("export-all", "crea il bundle .phx (import <file> sull'altro PC)"),
        item("mcp", "server MCP: dà a Claude la memoria delle sessioni passate"),
        item("~uso 5h/7g", "stima LOCALE del volume token (non la % ufficiale dei limiti)"),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · Portare una sessione su un altro PC", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Funziona con lo STESSO account Claude o con uno DIVERSO:", Style::default().fg(th.dim))),
        Line::from(Span::styled("  il .phx non contiene credenziali; l'import è tutto locale.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Cosa viene spostato", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · il transcript + le sue sottocartelle (sub-agenti e", Style::default().fg(th.fg))),
        Line::from(Span::styled("     workflow), tutto in un unico file .phx", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · NON il codice del progetto, NON il login/credenziali", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  1) Esporta (sul PC di partenza)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · nell'app: premi  x  (impacchetta le sessioni in vista)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · da terminale:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all                 (tutte)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --project NOME  (un progetto)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --out D:\\f.phx  (percorso scelto)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · esce in  Desktop\\phosphor-sessioni-*.phx", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  2) Trasferisci", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · copia il .phx sull'altro PC (USB, cloud, email…)", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  3) Importa (sul PC di destinazione)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · nell'app: premi  i  → si apre un selettore di file:", Style::default().fg(th.fg))),
        Line::from(Span::styled("       sfoglia le cartelle, scegli il .phx, poi conferma", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · da terminale:  phosphor import <file.phx>", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · SICURO: non sovrascrive, salta i file già presenti,", Style::default().fg(th.dim))),
        Line::from(Span::styled("       chiede sempre conferma; aggiunge solo ciò che manca", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  4) Riprendi la conversazione (non solo vederla)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · servono Claude installato e un login valido su quel", Style::default().fg(th.fg))),
        Line::from(Span::styled("       PC (anche un account DIVERSO va bene)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · serve la cartella di lavoro del progetto:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         stesso percorso  →  seleziona e premi  r", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            (oppure  claude --resume <id>)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         percorso diverso →  porta il codice (es. con git),", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            poi premi  r : se la cartella non", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            esiste, Phosphor apre un selettore →", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            scegli quella locale e riprende", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            (forka da solo; salva il remap)", Style::default().fg(th.dim))),
        Line::from(Span::styled("     · il CODICE non è nel .phx: portalo a parte (git/copia)", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · La flotta: i tuoi altri PC via SSH (tasto F)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Il .phx serve quando l'altro PC è SPENTO. Se è acceso,", Style::default().fg(th.fg))),
        Line::from(Span::styled("  vai tu dalla sessione invece di spostarla: niente copie,", Style::default().fg(th.fg))),
        Line::from(Span::styled("  niente remap, claude riprende LÀ nella cartella giusta.", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  Configura (una volta sola)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     phosphor remote add <alias>     es. pc-casa o utente@host", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (l'alias viene da ~/.ssh/config; Phosphor NON salva host,", Style::default().fg(th.dim))),
        Line::from(Span::styled("   utenti o chiavi — solo l'alias. Canale cifrato da SSH.)", Style::default().fg(th.dim))),
        Line::from(Span::styled("  Sull'altro PC servono: sshd attivo, phosphor nel PATH,", Style::default().fg(th.dim))),
        Line::from(Span::styled("  claude loggato (paga l'account di QUELLA macchina).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Usa", Style::default().fg(th.accent))),
        Line::from(Span::styled("     F          interroga gli host e unisce le sessioni [alias]", Style::default().fg(th.fg))),
        Line::from(Span::styled("     host:nome  filtra per PC ( host:qui  = solo locali)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     agent:codex / agent:claude  filtra per agente", Style::default().fg(th.fg))),
        Line::from(Span::styled("     r          su una riga [alias]: apre  ssh -t <alias>", Style::default().fg(th.fg))),
        Line::from(Span::styled("                phosphor resume-here <id>  → riprende LÀ", Style::default().fg(th.fg))),
        Line::from(Span::styled("  Sulle righe remote restano attivi r/dettaglio/note/preferiti;", Style::default().fg(th.dim))),
        Line::from(Span::styled("  le azioni sui file (lettura, export, cancella…) sono locali.", Style::default().fg(th.dim))),
        Line::from(Span::styled("  Da terminale:  phosphor fleet  (riassunto per host).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · Dare a Claude la memoria delle sessioni (MCP)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Cos'è: con  phosphor mcp  Claude Code può cercare e", Style::default().fg(th.fg))),
        Line::from(Span::styled("  rileggere le tue conversazioni PASSATE durante una nuova", Style::default().fg(th.fg))),
        Line::from(Span::styled("  chat (\"cosa avevo deciso su X?\"). 100% locale e in sola", Style::default().fg(th.fg))),
        Line::from(Span::styled("  lettura: nessuna rete, parla con Claude via stdin/stdout.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Come si attiva (una volta sola)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     claude mcp add phosphor -- phosphor mcp", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (phosphor dev'essere nel PATH; poi riapri Claude Code)", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Cosa può fare Claude tramite Phosphor", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · search_sessions — trova sessioni (stessi filtri di  / :", Style::default().fg(th.fg))),
        Line::from(Span::styled("                       project: model: file: tool: after:…)", Style::default().fg(th.dim))),
        Line::from(Span::styled("   · read_session    — legge il transcript di una sessione", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · search_content  — cerca nel TESTO di tutte le chat", Style::default().fg(th.fg))),
        Line::from(Span::styled("  Tu chiedi a Claude in linguaggio naturale; sceglie lui", Style::default().fg(th.dim))),
        Line::from(Span::styled("  quale strumento usare. Tutto resta sul tuo PC.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Tutto è cliccabile: tab, header, bottoni, chip, temi.", Style::default().fg(th.dim))),
    ]
}

/// The panel in English.
///
/// A whole second function rather than a `t!()` pair on every line: this is a
/// hundred and forty lines of continuous prose, and prose reads and is revised
/// as a document, not as a column of alternatives. The keys in the left-hand
/// column stay identical in both, which is what keeps the two in step — a test
/// checks that neither language has a command the other lacks.
fn lines_en(th: &Theme) -> Vec<Line<'static>> {
    let item = |k: &str, d: &str| Line::from(vec![
        Span::styled(format!("  {:<12}", k), Style::default().fg(th.accent)),
        Span::styled(d.to_string(), Style::default().fg(th.fg)),
    ]);
    vec![
        Line::raw(""),
        Line::from(Span::styled("  SYMBOLS", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↳", "resumed session, or one from /compact (continues the previous)"),
        item("★ · 📝 · ◉", "favorite  ·  has a note  ·  selected (multi-select)"),
        item("◆", "a Codex session (~/.codex/sessions) rather than Claude Code: project name in a different colour, resumes with  codex resume . Filter:  agent:codex . Tokens and cost are OpenAI's (the \"gpt\" prices in phosphor.json)."),
        item("⚠ history", "Claude Code DELETES its own transcripts after  cleanupPeriodDays  days — 30 by default, at startup, with no recycle bin: that is how a project untouched for a month disappears from here. Phosphor asks about it on the first run; you can also do it from the command line with  phosphor retention 3650  (it changes that one number in ~/.claude/settings.json and keeps a copy of the file). Codex has nothing like it: it does not prune by date. Against everything else — disk cleaners, sync, manual deletion — use  phosphor vault on ."),
        item("⛁", "saved by the vault: its agent deleted the transcript, but it survives as a hard link in ~/.claude/phosphor-vault. It is complete — tokens, conversation, all of it — and  V  puts it back where it belongs, resumable again. Turn it on with  phosphor vault on  (off by default: it is the one thing that writes to disk)."),
        item("⚱", "recovered from history.jsonl: Claude Code deleted the transcript (cleanupPeriodDays, 30 days by default). The prompts remain; no replies, tokens, cost or resume. Raise cleanupPeriodDays in ~/.claude/settings.json so you lose no more."),
        item("● ◐ ·", "state:  ● running   ◐ idle   · ended"),
        item("⏎", "the Enter key (opens the session detail)"),
        item("↑ ↓", "up/down arrows (move the selection)"),
        Line::from(Span::styled("  Usage tips scroll in the box at the top right (› …).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  COMMANDS", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↑↓ / scroll", "move the selection (without opening)"),
        item("Enter / click", "open the session detail"),
        item("right / .", "session menu: every action in one place"),
        item("+ / -", "expand/collapse the resumes of the selected conversation"),
        item("A", "expand/collapse EVERY resume at once"),
        item("⟳N ✓ / (certain)", "PROVEN link (the sessions share messages)"),
        item("(likely)", "grouping GUESSED from title+project+time"),
        item("v", "read the conversation (transcript) in-app"),
        item("g", "search the CONTENT of every conversation → open at the hit"),
        item("M", "export the conversation as Markdown (on the Desktop)"),
        item("*  ·  n", "favorite (★)  ·  note on the session (📝)"),
        item("N", "rename: your own title/alias shown in the list instead of the automatic one"),
        item("O  ·  y", "open the project folder  ·  copy the transcript path"),
        item("space", "select/deselect (◉) for bulk actions  ·  Esc clears"),
        item("in bulk", "with a selection active:  x bundle  ·  * favorites  ·  X delete (asks first)"),
        item("a", "explore sub-agents / workflows"),
        item("/", "filter the list — text + filters: project: model: file: tool: agent: host: after: before:"),
        item("f  ·  o/s", "state/★favorites filter  ·  sort column/direction"),
        item("m", "chart metric (or click the buttons)"),
        item("r  ·  e", "resume (claude --resume)  ·  export CSV/JSON"),
        item("x  ·  i", "export a .phx bundle  ·  import one (file picker + confirmation)"),
        item("H", "ARCHIVE the project (hides it in archived/, reversible) — restore from the CLI"),
        item("W", "WRAPPED: writes the year's summary card to the Desktop (PNG + SVG) — tokens, cost, energy, water. Anonymous: numbers only."),
        item("V", "RESTORE from the vault: puts the transcript back into its agent's own store (⛁ rows only)"),
        item("F", "FLEET: queries your other PCs over ssh and merges their sessions [alias]"),
        item("", "  (set up with:  phosphor remote add <ssh-alias> · on a remote row: r resumes THERE)"),
        item("D", "DELETE the session's project (double confirmation: re-type the name; offers a .phx backup)"),
        item("t/T  ·  p", "theme forward/back  ·  pixel graphics"),
        item("R  ·  Tab", "rescan  ·  switch view (or 1 2 3)  ·  q quit"),
        item("L", "switch language: English ⇄ italiano"),
        Line::raw(""),
        Line::from(Span::styled("  From the terminal  ›  phosphor …", Style::default().fg(th.accent))),
        item("find <text>", "full-text search across every session"),
        item("cost", "spend 24h/7d/30d · budget · top projects (--explain shows the arithmetic)"),
        item("limits", "plan (e.g. Max 20x) · limit-window reset"),
        item("watch", "live monitor with state-change alerts"),
        item("clean", "disk usage · empty-session cleanup (asks first)"),
        item("export-all", "create the .phx bundle (import <file> on the other PC)"),
        item("mcp", "MCP server: gives Claude recall over your past sessions"),
        item("~used 5h/7d", "LOCAL estimate of token volume (not the official limit %)"),
        Line::raw(""),
        Line::from(Span::styled("  GUIDE · Moving a session to another PC", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Works with the SAME Claude account or a DIFFERENT one:", Style::default().fg(th.dim))),
        Line::from(Span::styled("  a .phx holds no credentials; the import is entirely local.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  What travels", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · the transcript + its subfolders (sub-agents and", Style::default().fg(th.fg))),
        Line::from(Span::styled("     workflows), all in a single .phx file", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · NOT the project's code, NOT your login/credentials", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  1) Export (on the PC you are leaving)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · in the app: press  x  (packs the sessions in view)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · from the terminal:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all                 (everything)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --project NAME  (one project)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --out D:\\f.phx  (chosen path)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · lands in  Desktop\\phosphor-sessioni-*.phx", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  2) Transfer", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · copy the .phx to the other PC (USB, cloud, email…)", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  3) Import (on the destination PC)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · in the app: press  i  → a file picker opens:", Style::default().fg(th.fg))),
        Line::from(Span::styled("       browse the folders, choose the .phx, then confirm", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · from the terminal:  phosphor import <file.phx>", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · SAFE: never overwrites, skips files already there,", Style::default().fg(th.dim))),
        Line::from(Span::styled("       refuses paths that would escape the projects folder", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  4) Resume on the new PC", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · the code must be there too, in ITS own folder", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · if the path differs, add a remap in phosphor.json:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         \"pathRemaps\": { \"C:\\\\vecchio\": \"D:\\\\nuovo\" }", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · with a remap Phosphor FORKS the session, so the", Style::default().fg(th.dim))),
        Line::from(Span::styled("       original stays untouched on the first PC", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDE · Your other PCs, live (fleet)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Unlike the .phx, nothing is copied: Phosphor ASKS the other", Style::default().fg(th.fg))),
        Line::from(Span::styled("  machines over ssh and shows their sessions beside yours. No", Style::default().fg(th.fg))),
        Line::from(Span::styled("  remap needed — claude resumes THERE, in the right folder.", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  Set up (once)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     phosphor remote add <alias>     e.g. pc-home or user@host", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (the alias comes from ~/.ssh/config; Phosphor stores NO host,", Style::default().fg(th.dim))),
        Line::from(Span::styled("   user or key — only the alias. SSH provides the channel.)", Style::default().fg(th.dim))),
        Line::from(Span::styled("  The other PC needs: sshd running, phosphor on the PATH,", Style::default().fg(th.dim))),
        Line::from(Span::styled("  claude logged in (THAT machine's account pays).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Use", Style::default().fg(th.accent))),
        Line::from(Span::styled("     F          query the hosts and merge their sessions [alias]", Style::default().fg(th.fg))),
        Line::from(Span::styled("     host:name  filter by PC ( host:qui  = local only)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     agent:codex / agent:claude  filter by agent", Style::default().fg(th.fg))),
        Line::from(Span::styled("     r          on an [alias] row: opens  ssh -t <alias>", Style::default().fg(th.fg))),
        Line::from(Span::styled("                phosphor resume-here <id>  → resumes THERE", Style::default().fg(th.fg))),
        Line::from(Span::styled("  On remote rows r/detail/notes/favorites still work;", Style::default().fg(th.dim))),
        Line::from(Span::styled("  file actions (read, export, delete…) are local only.", Style::default().fg(th.dim))),
        Line::from(Span::styled("  From the terminal:  phosphor fleet  (per-host summary).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDE · Giving Claude memory of your sessions (MCP)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  What it is: with  phosphor mcp  Claude Code can search and", Style::default().fg(th.fg))),
        Line::from(Span::styled("  re-read your PAST conversations during a new chat (\"what", Style::default().fg(th.fg))),
        Line::from(Span::styled("  did I decide about X?\"). 100% local and read-only: no", Style::default().fg(th.fg))),
        Line::from(Span::styled("  network, it talks to Claude over stdin/stdout.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  How to turn it on (once)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     claude mcp add phosphor -- phosphor mcp", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (phosphor must be on the PATH; then reopen Claude Code)", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  What Claude can do through Phosphor", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · search_sessions — find sessions (the same filters as  / :", Style::default().fg(th.fg))),
        Line::from(Span::styled("                       project: model: file: tool: after:…)", Style::default().fg(th.dim))),
        Line::from(Span::styled("   · read_session    — reads a session's transcript", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · search_content  — searches the TEXT of every chat", Style::default().fg(th.fg))),
        Line::from(Span::styled("  You ask Claude in plain language; it picks the tool.", Style::default().fg(th.dim))),
        Line::from(Span::styled("  Everything stays on your PC.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Everything is clickable: tabs, headers, buttons, chips, themes.", Style::default().fg(th.dim))),
    ]
}
