//! The help panel's contents: what it says, and which row runs what.
//!
//! Kept out of `tui.rs` because this is text, not behaviour — a hundred and
//! forty lines of prose that used to sit in the middle of the renderer and
//! made both harder to read. The rendering (the box, the scrolling, the
//! clickable rows) stays with the rest of the drawing, in the parent.
//!
//! Since every row of this panel is also a CLICKABLE command, the two things
//! here belong together: change a row's leading key and [`action`] is the one
//! place that has to agree with it.

use super::*;

/// The action a help row runs when clicked, or 0 for the rows that are only
/// legend.
///
/// The key shown at the start of a row IS the row's identity, so it is what
/// this keys on: no parallel list to keep in step with the text.
pub(super) fn action(key: &str) -> u16 {
    match key {
        "⏎" => A_DETAIL,
        "v" => A_READ,
        "g" => A_GSEARCH,
        "M" => A_MARKDOWN,
        "N" => A_ALIAS,
        "a" => A_AGENTS,
        "/" => A_SEARCH,
        "m" => A_METRIC,
        "A" => A_EXPAND_ALL,
        "H" => A_ARCHIVE,
        "W" => A_WRAPPED,
        "V" => A_VAULT_RESTORE,
        "F" => A_FLEET,
        "D" => A_DELPROJECT,
        k if k.starts_with("*") => A_FAVORITE,
        k if k.starts_with("O") => A_OPENFOLDER,
        k if k.starts_with("f") => A_FILTER,
        k if k.starts_with("r") => A_RESUME,
        k if k.starts_with("x") => A_EXPBUNDLE,
        k if k.starts_with("t/T") => A_THEME_NEXT,
        k if k.starts_with("R") => A_RESCAN,
        _ => 0,
    }
}

/// Every line of the panel, styled. `'static` because the text is all literals
/// and the caller scrolls it.
pub(super) fn lines(th: &Theme) -> Vec<Line<'static>> {
    let item = |k: &str, d: &str| Line::from(vec![
        Span::styled(format!("  {:<12}", k), Style::default().fg(th.accent)),
        Span::styled(d.to_string(), Style::default().fg(th.fg)),
    ]);
    vec![
        Line::raw(""),
        Line::from(Span::styled("  LEGENDA SIMBOLI", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↳", "sessione ripresa o da /compact (continua la precedente)"),
        item("★ · 📝 · ◉", "preferito  ·  ha una nota  ·  selezionata (multi-select)"),
        item("◆", "sessione Codex (~/.codex/sessions) invece che Claude Code: nome del progetto in un altro colore, riprende con  codex resume . Filtro:  agent:codex . Token e costo sono quelli di OpenAI (prezzi \"gpt\" in phosphor.json)."),
        item("⚠ cronologia", "Claude Code cancella i suoi transcript dopo  cleanupPeriodDays  giorni — 30 di default, all'avvio, senza cestino: è così che spariscono i progetti fermi da un mese. Phosphor te lo chiede al primo avvio; puoi anche farlo da riga di comando con  phosphor retention 3650  (cambia solo quel numero in ~/.claude/settings.json e tiene una copia del file). Codex non ha nulla di simile: non pota per data. Contro tutto il resto — pulitori disco, sync, cancellazioni a mano — serve  phosphor vault on ."),
        item("⛁", "salvata dal vault: il suo agente ha cancellato il transcript, che però sopravvive come hard link in ~/.claude/phosphor-vault. È completa — token, conversazione, tutto — e  V  la rimette al suo posto, tornando riprendibile. Si accende con  phosphor vault on  (spento di default: è l'unica cosa che scrive su disco)."),
        item("⚱", "recuperata da history.jsonl: il transcript l'ha cancellato Claude Code (cleanupPeriodDays, 30 giorni di default). Restano i prompt; niente risposte, token, costo o riprendi. Alza cleanupPeriodDays in ~/.claude/settings.json per non perderne altre."),
        item("● ◐ ·", "stato:  ● attiva   ◐ in pausa (idle)   · conclusa"),
        item("⏎", "tasto Invio (apre il dettaglio della sessione)"),
        item("↑ ↓", "frecce su/giù (muovono la selezione)"),
        Line::from(Span::styled("  In alto a destra scorrono pillole d'uso (› …).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  COMANDI RAPIDI", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        item("↑↓ / scroll", "muovi selezione (senza aprire)"),
        item("Invio / click", "apri dettaglio della sessione"),
        item("destro / .", "menù sessione: tutte le azioni in un colpo solo"),
        item("+ / -", "espandi/comprimi le riprese della conversazione selezionata"),
        item("A", "espandi/comprimi TUTTE le riprese in una volta"),
        item("⟳N ✓ / (certo)", "link PROVATO (le sessioni condividono messaggi)"),
        item("(probabile)", "raggruppamento STIMATO da titolo+progetto+tempo"),
        item("v", "leggi la conversazione (transcript) in-app"),
        item("g", "cerca nel CONTENUTO di tutte le conversazioni → apri al punto"),
        item("M", "esporta la conversazione in Markdown (sul Desktop)"),
        item("*  ·  n", "preferito (★)  ·  nota sulla sessione (📝)"),
        item("N", "rinomina: titolo/alias tuo mostrato in lista al posto di quello automatico"),
        item("O  ·  y", "apri la cartella del progetto  ·  copia il percorso del transcript"),
        item("spazio", "seleziona/deseleziona (◉) per azioni in blocco  ·  Esc azzera"),
        item("in blocco", "con selezione attiva:  x bundle  ·  * preferiti  ·  X cancella (conferma)"),
        item("a", "esplora sub-agenti / workflow"),
        item("/", "filtra la lista — testo + filtri: project: model: file: tool: agent: host: after: before:"),
        item("f  ·  o/s", "filtro stato/★preferiti  ·  ordina colonna/direzione"),
        item("m", "metrica grafici (o click sui bottoni)"),
        item("r  ·  e", "riprendi (claude --resume)  ·  export CSV/JSON"),
        item("x  ·  i", "esporta bundle .phx  ·  importa (selettore file + conferma)"),
        item("H", "ARCHIVIA il progetto (lo nasconde in archived/, reversibile) — ripristina da CLI"),
        item("W", "WRAPPED: genera sul Desktop la card riassuntiva dell'anno (PNG + SVG) — token, costo, energia, acqua. Anonima: solo numeri."),
        item("V", "RIPRISTINA dal vault: rimette il transcript nel magazzino del suo agente (solo righe ⛁)"),
        item("F", "FLOTTA: interroga i tuoi altri PC via ssh e unisce le loro sessioni [alias]"),
        item("", "  (configura con:  phosphor remote add <alias-ssh> · su remoto: r riprende LÀ)"),
        item("D", "CANCELLA il progetto della sessione (doppia conferma: riscrivi il nome; offre backup .phx)"),
        item("t/T  ·  p", "tema avanti/indietro  ·  grafica pixel"),
        item("R  ·  Tab", "rescan  ·  cambia vista (o 1 2 3)  ·  q esci"),
        Line::raw(""),
        Line::from(Span::styled("  Da terminale  ›  phosphor …", Style::default().fg(th.accent))),
        item("find <testo>", "ricerca full-text in tutte le sessioni"),
        item("cost", "spesa 24h/7g/30g · budget · top progetti"),
        item("limits", "piano (es. Max 20x) · reset finestra limiti"),
        item("watch", "monitor live con avvisi di stato"),
        item("clean", "spazio disco · pulizia vuote (con conferma)"),
        item("export-all", "crea il bundle .phx (import <file> sull'altro PC)"),
        item("mcp", "server MCP: dà a Claude la memoria delle sessioni passate"),
        item("~uso 5h/7g", "stima LOCALE del volume token (non la % ufficiale dei limiti)"),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · Portare una sessione su un altro PC", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Funziona con lo STESSO account Claude o con uno DIVERSO:", Style::default().fg(th.dim))),
        Line::from(Span::styled("  il .phx non contiene credenziali; l'import è tutto locale.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Cosa viene spostato", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · il transcript + le sue sottocartelle (sub-agenti e", Style::default().fg(th.fg))),
        Line::from(Span::styled("     workflow), tutto in un unico file .phx", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · NON il codice del progetto, NON il login/credenziali", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  1) Esporta (sul PC di partenza)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · nell'app: premi  x  (impacchetta le sessioni in vista)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · da terminale:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all                 (tutte)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --project NOME  (un progetto)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         phosphor export-all --out D:\\f.phx  (percorso scelto)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · esce in  Desktop\\phosphor-sessioni-*.phx", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  2) Trasferisci", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · copia il .phx sull'altro PC (USB, cloud, email…)", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  3) Importa (sul PC di destinazione)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · nell'app: premi  i  → si apre un selettore di file:", Style::default().fg(th.fg))),
        Line::from(Span::styled("       sfoglia le cartelle, scegli il .phx, poi conferma", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · da terminale:  phosphor import <file.phx>", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · SICURO: non sovrascrive, salta i file già presenti,", Style::default().fg(th.dim))),
        Line::from(Span::styled("       chiede sempre conferma; aggiunge solo ciò che manca", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  4) Riprendi la conversazione (non solo vederla)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     · servono Claude installato e un login valido su quel", Style::default().fg(th.fg))),
        Line::from(Span::styled("       PC (anche un account DIVERSO va bene)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     · serve la cartella di lavoro del progetto:", Style::default().fg(th.fg))),
        Line::from(Span::styled("         stesso percorso  →  seleziona e premi  r", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            (oppure  claude --resume <id>)", Style::default().fg(th.fg))),
        Line::from(Span::styled("         percorso diverso →  porta il codice (es. con git),", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            poi premi  r : se la cartella non", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            esiste, Phosphor apre un selettore →", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            scegli quella locale e riprende", Style::default().fg(th.fg))),
        Line::from(Span::styled("                            (forka da solo; salva il remap)", Style::default().fg(th.dim))),
        Line::from(Span::styled("     · il CODICE non è nel .phx: portalo a parte (git/copia)", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · La flotta: i tuoi altri PC via SSH (tasto F)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Il .phx serve quando l'altro PC è SPENTO. Se è acceso,", Style::default().fg(th.fg))),
        Line::from(Span::styled("  vai tu dalla sessione invece di spostarla: niente copie,", Style::default().fg(th.fg))),
        Line::from(Span::styled("  niente remap, claude riprende LÀ nella cartella giusta.", Style::default().fg(th.fg))),
        Line::raw(""),
        Line::from(Span::styled("  Configura (una volta sola)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     phosphor remote add <alias>     es. pc-casa o utente@host", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (l'alias viene da ~/.ssh/config; Phosphor NON salva host,", Style::default().fg(th.dim))),
        Line::from(Span::styled("   utenti o chiavi — solo l'alias. Canale cifrato da SSH.)", Style::default().fg(th.dim))),
        Line::from(Span::styled("  Sull'altro PC servono: sshd attivo, phosphor nel PATH,", Style::default().fg(th.dim))),
        Line::from(Span::styled("  claude loggato (paga l'account di QUELLA macchina).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Usa", Style::default().fg(th.accent))),
        Line::from(Span::styled("     F          interroga gli host e unisce le sessioni [alias]", Style::default().fg(th.fg))),
        Line::from(Span::styled("     host:nome  filtra per PC ( host:qui  = solo locali)", Style::default().fg(th.fg))),
        Line::from(Span::styled("     agent:codex / agent:claude  filtra per agente", Style::default().fg(th.fg))),
        Line::from(Span::styled("     r          su una riga [alias]: apre  ssh -t <alias>", Style::default().fg(th.fg))),
        Line::from(Span::styled("                phosphor resume-here <id>  → riprende LÀ", Style::default().fg(th.fg))),
        Line::from(Span::styled("  Sulle righe remote restano attivi r/dettaglio/note/preferiti;", Style::default().fg(th.dim))),
        Line::from(Span::styled("  le azioni sui file (lettura, export, cancella…) sono locali.", Style::default().fg(th.dim))),
        Line::from(Span::styled("  Da terminale:  phosphor fleet  (riassunto per host).", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  GUIDA · Dare a Claude la memoria delle sessioni (MCP)", Style::default().fg(th.accent).add_modifier(Modifier::BOLD))),
        Line::from(Span::styled("  Cos'è: con  phosphor mcp  Claude Code può cercare e", Style::default().fg(th.fg))),
        Line::from(Span::styled("  rileggere le tue conversazioni PASSATE durante una nuova", Style::default().fg(th.fg))),
        Line::from(Span::styled("  chat (\"cosa avevo deciso su X?\"). 100% locale e in sola", Style::default().fg(th.fg))),
        Line::from(Span::styled("  lettura: nessuna rete, parla con Claude via stdin/stdout.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Come si attiva (una volta sola)", Style::default().fg(th.accent))),
        Line::from(Span::styled("     claude mcp add phosphor -- phosphor mcp", Style::default().fg(th.fg))),
        Line::from(Span::styled("  (phosphor dev'essere nel PATH; poi riapri Claude Code)", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Cosa può fare Claude tramite Phosphor", Style::default().fg(th.accent))),
        Line::from(Span::styled("   · search_sessions — trova sessioni (stessi filtri di  / :", Style::default().fg(th.fg))),
        Line::from(Span::styled("                       project: model: file: tool: after:…)", Style::default().fg(th.dim))),
        Line::from(Span::styled("   · read_session    — legge il transcript di una sessione", Style::default().fg(th.fg))),
        Line::from(Span::styled("   · search_content  — cerca nel TESTO di tutte le chat", Style::default().fg(th.fg))),
        Line::from(Span::styled("  Tu chiedi a Claude in linguaggio naturale; sceglie lui", Style::default().fg(th.dim))),
        Line::from(Span::styled("  quale strumento usare. Tutto resta sul tuo PC.", Style::default().fg(th.dim))),
        Line::raw(""),
        Line::from(Span::styled("  Tutto è cliccabile: tab, header, bottoni, chip, temi.", Style::default().fg(th.dim))),
    ]
}
